from app import create_app
from extensions import db
from models.destination import Destination

GLOBAL_DESTINATIONS = [
    # ── Asia (15) ──
    {"name": "Taj Mahal", "region": "Agra", "country": "India", "lat": 27.1751, "lng": 78.0421, "description": "Ivory-white marble mausoleum, one of the Seven Wonders", "category": "heritage", "best_time_to_visit": "October to March", "entry_fee_display": "₹1100", "rating": 4.9, "image_url": "https://images.unsplash.com/photo-1564507592333-c60657ece523?q=80&w=1000&auto=format&fit=crop", "highlights": "Marble architecture, Mughal gardens, Sunrise views"},
    {"name": "Great Wall of China", "region": "Huairou", "country": "China", "lat": 40.4319, "lng": 116.5704, "description": "Ancient series of walls spanning 21,000 km", "category": "heritage", "best_time_to_visit": "April to October", "entry_fee_display": "$45", "rating": 4.8, "image_url": "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?q=80&w=1000&auto=format&fit=crop", "highlights": "Watchtowers, Mountain views, Hiking trails"},
    {"name": "Angkor Wat", "region": "Siem Reap", "country": "Cambodia", "lat": 13.4125, "lng": 103.8670, "description": "Largest religious monument in the world", "category": "heritage", "best_time_to_visit": "November to February", "entry_fee_display": "$37", "rating": 4.8, "image_url": "https://images.unsplash.com/photo-1569660070214-4297a2246e27?q=80&w=1000&auto=format&fit=crop", "highlights": "Temple architecture, Sunrise, Khmer history"},
    {"name": "Mount Fuji", "region": "Honshu", "country": "Japan", "lat": 35.3606, "lng": 138.7274, "description": "Iconic snow-capped volcano, UNESCO World Heritage", "category": "nature", "best_time_to_visit": "July to August", "entry_fee_display": "Free", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c93?q=80&w=1000&auto=format&fit=crop", "highlights": "Volcanic scenery, Lake Kawaguchi, Hiking"},
    {"name": "Petra", "region": "Ma'an", "country": "Jordan", "lat": 30.3285, "lng": 35.4444, "description": "Rose-red city carved into rock, ancient Nabataean capital", "category": "heritage", "best_time_to_visit": "March to May", "entry_fee_display": "$70", "rating": 4.8, "image_url": "https://images.unsplash.com/photo-1579606035142-54313408027a?q=80&w=1000&auto=format&fit=crop", "highlights": "Treasury, Siq canyon, Night show"},
    {"name": "Bali", "region": "Lesser Sunda Islands", "country": "Indonesia", "lat": -8.3405, "lng": 115.0920, "description": "Island of temples, rice terraces, and surf breaks", "category": "island", "best_time_to_visit": "April to October", "entry_fee_display": "Varies", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1000&auto=format&fit=crop", "highlights": "Rice terraces, Beaches, Spiritual temples"},
    {"name": "Ha Long Bay", "region": "Quang Ninh", "country": "Vietnam", "lat": 20.9101, "lng": 107.1839, "description": "Emerald waters dotted with thousands of limestone karsts", "category": "nature", "best_time_to_visit": "March to May", "entry_fee_display": "$50", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=1000&auto=format&fit=crop", "highlights": "Limestone karsts, Boat cruises, Emerald water"},
    {"name": "Bagan", "region": "Mandalay", "country": "Myanmar", "lat": 21.1717, "lng": 94.8585, "description": "Ancient city with over 2,000 Buddhist temples and pagodas", "category": "heritage", "best_time_to_visit": "November to February", "entry_fee_display": "$30", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1540611025311-01df3cccf53c?q=80&w=1000&auto=format&fit=crop", "highlights": "Pagodas, Hot air balloons, Sunrise"},
    {"name": "Hampi", "region": "Karnataka", "country": "India", "lat": 15.3350, "lng": 76.4600, "description": "Ruins of the Vijayanagara Empire amid boulder-strewn landscape", "category": "heritage", "best_time_to_visit": "October to February", "entry_fee_display": "Free", "rating": 4.5, "image_url": "https://images.unsplash.com/photo-1589185340151-369600360a30?q=80&w=1000&auto=format&fit=crop", "highlights": "Temples, Boulder landscapes, Ruins"},
    {"name": "Boracay", "region": "Western Visayas", "country": "Philippines", "lat": 11.9674, "lng": 121.9248, "description": "White-sand beach island, world-class sunsets", "category": "island", "best_time_to_visit": "November to April", "entry_fee_display": "Free", "rating": 4.4, "image_url": "https://images.unsplash.com/photo-1559628233-1710b6f06e24?q=80&w=1000&auto=format&fit=crop", "highlights": "White sand, Sunset, Water sports"},
    {"name": "Chiang Mai", "region": "Northern Thailand", "country": "Thailand", "lat": 18.7883, "lng": 98.9853, "description": "Lanna kingdom temples, night bazaars, mountain trails", "category": "city", "best_time_to_visit": "November to February", "entry_fee_display": "Free", "rating": 4.5, "image_url": "https://images.unsplash.com/photo-1585129777188-9f3533dc8f0a?q=80&w=1000&auto=format&fit=crop", "highlights": "Temples, Night markets, Mountain trekking"},
    {"name": "Sigiriya", "region": "Central Province", "country": "Sri Lanka", "lat": 7.9572, "lng": 80.7603, "description": "Ancient rock fortress with frescoes and lion's paw gateway", "category": "heritage", "best_time_to_visit": "May to September", "entry_fee_display": "$30", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1588598116719-f0935521707c?q=80&w=1000&auto=format&fit=crop", "highlights": "Rock fortress, Frescoes, Lion paw"},
    {"name": "Komodo Island", "region": "East Nusa Tenggara", "country": "Indonesia", "lat": -8.5500, "lng": 119.4833, "description": "Home of the Komodo dragon, pristine coral reefs", "category": "nature", "best_time_to_visit": "April to December", "entry_fee_display": "$25", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1516690561799-46d8f79f6ad2?q=80&w=1000&auto=format&fit=crop", "highlights": "Komodo dragons, Snorkeling, Pristine beaches"},
    {"name": "Lhasa Potala Palace", "region": "Tibet", "country": "China", "lat": 29.6575, "lng": 91.1172, "description": "Former winter palace of the Dalai Lama at 3,700 m", "category": "heritage", "best_time_to_visit": "May to October", "entry_fee_display": "$40", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1523730404492-63628267463f?q=80&w=1000&auto=format&fit=crop", "highlights": "Tibetan culture, Potala Palace, High altitude"},
    {"name": "Dubai Burj Khalifa", "region": "Dubai", "country": "United Arab Emirates", "lat": 25.1972, "lng": 55.2744, "description": "World's tallest building at 828 m, observation deck", "category": "city", "best_time_to_visit": "November to March", "entry_fee_display": "$45", "rating": 4.5, "image_url": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1000&auto=format&fit=crop", "highlights": "Tallest building, Observation deck, City skyline"},

    # ── Europe (15) ──
    {"name": "Eiffel Tower", "region": "Paris", "country": "France", "lat": 48.8584, "lng": 2.2945, "description": "Iconic wrought-iron lattice tower, symbol of Paris", "category": "heritage", "best_time_to_visit": "June to August", "entry_fee_display": "$28", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1511739001486-6bfe10ec785f?q=80&w=1000&auto=format&fit=crop", "highlights": "Iconic tower, Paris views, Iron architecture"},
    {"name": "Colosseum", "region": "Rome", "country": "Italy", "lat": 41.8902, "lng": 12.4922, "description": "Ancient Roman amphitheatre, largest ever built", "category": "heritage", "best_time_to_visit": "April to June", "entry_fee_display": "$18", "rating": 4.8, "image_url": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1000&auto=format&fit=crop", "highlights": "Roman history, Gladiator arena, Amphitheatre"},
    {"name": "Sagrada Familia", "region": "Barcelona", "country": "Spain", "lat": 41.4036, "lng": 2.1744, "description": "Gaudi's unfinished basilica, under construction since 1882", "category": "heritage", "best_time_to_visit": "May to September", "entry_fee_display": "$25", "rating": 4.8, "image_url": "https://images.unsplash.com/photo-1583778176462-506839052114?q=80&w=1000&auto=format&fit=crop", "highlights": "Gaudi architecture, Mosaic details, Stained glass"},
    {"name": "Santorini", "region": "Cyclades", "country": "Greece", "lat": 36.3932, "lng": 25.4615, "description": "Volcanic island with iconic blue-domed churches", "category": "island", "best_time_to_visit": "May to September", "entry_fee_display": "Free", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=1000&auto=format&fit=crop", "highlights": "Blue domes, Sunset views, Aegean Sea"},
    {"name": "Big Ben", "region": "Westminster", "country": "United Kingdom", "lat": 51.5007, "lng": -0.1246, "description": "Iconic clock tower at the Houses of Parliament", "category": "heritage", "best_time_to_visit": "May to September", "entry_fee_display": "Free", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?q=80&w=1000&auto=format&fit=crop", "highlights": "Clock tower, Parliament, Westminster"},
    {"name": "Acropolis", "region": "Athens", "country": "Greece", "lat": 37.9715, "lng": 23.7267, "description": "Ancient citadel atop a rocky outcrop, home of the Parthenon", "category": "heritage", "best_time_to_visit": "April to June", "entry_fee_display": "$22", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1555992336-0aด้m8c61b3a?q=80&w=1000&auto=format&fit=crop", "highlights": "Parthenon, Ancient ruins, Athens view"},
    {"name": "Neuschwanstein Castle", "region": "Bavaria", "country": "Germany", "lat": 47.5576, "lng": 10.7498, "description": "19th-century Romanesque Revival palace, fairy-tale castle", "category": "heritage", "best_time_to_visit": "June to August", "entry_fee_display": "$18", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1000&auto=format&fit=crop", "highlights": "Fairy-tale castle, Bavarian Alps, Scenic views"},
    {"name": "St. Peter's Basilica", "region": "Vatican City", "country": "Vatican City", "lat": 41.9022, "lng": 12.4539, "description": "Largest church in the world, Renaissance masterpiece", "category": "heritage", "best_time_to_visit": "April to June", "entry_fee_display": "Free", "rating": 4.8, "image_url": "https://images.unsplash.com/photo-1531572706446-793d99d65744?q=80&w=1000&auto=format&fit=crop", "highlights": "Renaissance art, Michelangelo, Vatican history"},
    {"name": "Charles Bridge", "region": "Prague", "country": "Czech Republic", "lat": 50.0865, "lng": 14.4114, "description": "Historic stone bridge across the Vltava River", "category": "heritage", "best_time_to_visit": "May to September", "entry_fee_display": "Free", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1541849548-99417502f424?q=80&w=1000&auto=format&fit=crop", "highlights": "Stone bridge, Vltava River, Prague views"},
    {"name": "Edinburgh Castle", "region": "Edinburgh", "country": "United Kingdom", "lat": 55.9482, "lng": -3.1993, "description": "Historic fortress dominating Edinburgh's skyline", "category": "heritage", "best_time_to_visit": "June to August", "entry_fee_display": "Free", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1531161880999-513319a67f7b?q=80&w=1000&auto=format&fit=crop", "highlights": "Historic fortress, Edinburgh view, Castle architecture"},
    {"name": "Amalfi Coast", "region": "Campania", "country": "Italy", "lat": 40.6333, "lng": 14.6029, "description": "Dramatic coastline with cliffside villages and lemon groves", "category": "nature", "best_time_to_visit": "May to September", "entry_fee_display": "Free", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1000&auto=format&fit=crop", "highlights": "Cliffside villages, Lemon groves, Coastline views"},
    {"name": "Plitvice Lakes", "region": "Lika-Senj", "country": "Croatia", "lat": 44.8654, "lng": 15.5820, "description": "Cascading turquoise lakes and waterfalls, UNESCO site", "category": "nature", "best_time_to_visit": "May to September", "entry_fee_display": "$30", "rating": 4.7, "image_url": "https://images.unsplash.com/photo-1548567117-8033907b113b?q=80&w=1000&auto=format&fit=crop", "highlights": "Turquoise lakes, Waterfalls, UNESCO site"},
    {"name": "Swiss Alps (Jungfrau)", "region": "Bernese Oberland", "country": "Switzerland", "lat": 46.5366, "lng": 7.9633, "description": "Iconic Alpine peak, Top of Europe railway station", "category": "nature", "best_time_to_visit": "June to August", "entry_fee_display": "$150", "rating": 4.8, "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000&auto=format&fit=crop", "highlights": "Alpine peaks, Railway station, Snow-capped mountains"},
    {"name": "Cliffs of Moher", "region": "County Clare", "country": "Ireland", "lat": 52.9715, "lng": -9.4264, "description": "Sea cliffs rising 214 m above the Atlantic Ocean", "category": "nature", "best_time_to_visit": "May to September", "entry_fee_display": "Free", "rating": 4.5, "image_url": "https://images.unsplash.com/photo-1518544801976-3e159e50e5bb?q=80&w=1000&auto=format&fit=crop", "highlights": "Sea cliffs, Atlantic Ocean, Coastal views"},
    {"name": "Northern Lights (Tromsø)", "region": "Troms", "country": "Norway", "lat": 69.6492, "lng": 18.9553, "description": "Gateway city to the Arctic aurora borealis", "category": "nature", "best_time_to_visit": "September to March", "entry_fee_display": "Free", "rating": 4.6, "image_url": "https://images.unsplash.com/photo-1531366930499-81d8a8c992d1?q=80&w=1000&auto=format&fit=crop", "highlights": "Aurora borealis, Arctic scenery, Tromsø city"},

    # ── Americas (15) ──
    {"name": "Statue of Liberty",      "region": "New York",          "country": "United States",  "lat": 40.6892,  "lng": -74.0445, "description": "Colossal neoclassical sculpture, gift from France",            "category": "heritage"},
    {"name": "Machu Picchu",           "region": "Cusco",             "country": "Peru",           "lat": -13.1631, "lng": -72.5450, "description": "15th-century Inca citadel high in the Andes",                "category": "heritage"},
    {"name": "Christ the Redeemer",    "region": "Rio de Janeiro",    "country": "Brazil",         "lat": -22.9519, "lng": -43.2105, "description": "Art Deco statue atop Corcovado mountain",                   "category": "heritage"},
    {"name": "Grand Canyon",           "region": "Arizona",           "country": "United States",  "lat": 36.1069,  "lng": -112.1129,"description": "Mile-deep gorge carved by the Colorado River",                "category": "nature"},
    {"name": "Niagara Falls",          "region": "Ontario/New York",  "country": "Canada",         "lat": 43.0896,  "lng": -79.0849, "description": "Massive waterfalls on the US-Canada border",                 "category": "nature"},
    {"name": "Chichen Itza",           "region": "Yucatan",           "country": "Mexico",         "lat": 20.6843,  "lng": -88.5678, "description": "Maya pyramid complex, El Castillo temple",                  "category": "heritage"},
    {"name": "Iguazu Falls",           "region": "Misiones",          "country": "Argentina",      "lat": -25.6953, "lng": -54.4367, "description": "Spectacular waterfall system on the Argentina-Brazil border",  "category": "nature"},
    {"name": "Banff National Park",    "region": "Alberta",           "country": "Canada",         "lat": 51.4968,  "lng": -115.9281,"description": "Rocky Mountain park with turquoise glacial lakes",            "category": "nature"},
    {"name": "Torres del Paine",       "region": "Magallanes",        "country": "Chile",          "lat": -50.9423, "lng": -73.4068, "description": "Patagonian granite towers and glacial lakes",                "category": "nature"},
    {"name": "Yellowstone",            "region": "Wyoming",           "country": "United States",  "lat": 44.4280,  "lng": -110.5885,"description": "World's first national park, geysers and hot springs",       "category": "nature"},
    {"name": "Antigua Guatemala",      "region": "Sacatepequez",      "country": "Guatemala",      "lat": 14.5586,  "lng": -90.7295, "description": "Colonial city with volcano views and Mayan ruins nearby",      "category": "heritage"},
    {"name": "Cartagena Walled City",  "region": "Bolivar",           "country": "Colombia",       "lat": 10.3910,  "lng": -75.5144, "description": "Fortified colonial city on the Caribbean coast",              "category": "heritage"},
    {"name": "Galapagos Islands",      "region": "Galapagos",         "country": "Ecuador",        "lat": -0.9538,  "lng": -90.9656, "description": "Volcanic archipelago famous for unique wildlife",              "category": "nature"},
    {"name": "Monument Valley",        "region": "Arizona/Utah",      "country": "United States",  "lat": 36.9983,  "lng": -110.0985,"description": "Iconic sandstone buttes on Navajo Nation land",               "category": "nature"},
    {"name": "Havana Old City",        "region": "La Habana",         "country": "Cuba",           "lat": 23.1136,  "lng": -82.3666, "description": "Colourful colonial architecture and classic cars",             "category": "heritage"},

    # ── Africa (10) ──
    {"name": "Pyramids of Giza",       "region": "Giza",              "country": "Egypt",          "lat": 29.9792,  "lng": 31.1342,  "description": "Last surviving Wonder of the Ancient World",                   "category": "heritage"},
    {"name": "Table Mountain",         "region": "Cape Town",         "country": "South Africa",   "lat": -33.9628, "lng": 18.4098,  "description": "Flat-topped mountain with panoramic views over Cape Town",     "category": "nature"},
    {"name": "Victoria Falls",         "region": "Livingstone",       "country": "Zimbabwe",       "lat": -17.9243, "lng": 25.8572,  "description": "World's largest curtain of falling water, 'Smoke that Thunders'","category": "nature"},
    {"name": "Serengeti",              "region": "Arusha",            "country": "Tanzania",       "lat": -2.3333,  "lng": 34.8333,  "description": "Vast savanna ecosystem, Great Migration wildlife spectacle",    "category": "nature"},
    {"name": "Marrakech Medina",       "region": "Marrakech-Safi",    "country": "Morocco",        "lat": 31.6258,  "lng": -7.9891,  "description": "Labyrinthine old city with souks, palaces, and gardens",       "category": "heritage"},
    {"name": "Cape of Good Hope",      "region": "Western Cape",      "country": "South Africa",   "lat": -34.3568, "lng": 18.4742,  "description": "Rocky headland at the tip of the Cape Peninsula",              "category": "nature"},
    {"name": "Okavango Delta",         "region": "North-West",        "country": "Botswana",       "lat": -19.5000, "lng": 22.9667,  "description": "World's largest inland delta, wildlife paradise",              "category": "nature"},
    {"name": "Luxor Temple",           "region": "Luxor",             "country": "Egypt",          "lat": 25.6997,  "lng": 32.6390,  "description": "Ancient Egyptian temple complex on the east bank of the Nile",  "category": "heritage"},
    {"name": "Blyde River Canyon",     "region": "Mpumalanga",        "country": "South Africa",   "lat": -24.5740, "lng": 30.8120,  "description": "Largest green canyon in the world, dramatic viewpoints",       "category": "nature"},
    {"name": "Zanzibar Stone Town",    "region": "Zanzibar",          "country": "Tanzania",       "lat": -6.1622,  "lng": 39.1920,  "description": "Historic Swahili coastal town with spice markets",              "category": "heritage"},

    # ── Oceania (5) ──
    {"name": "Sydney Opera House",     "region": "Sydney",            "country": "Australia",      "lat": -33.8568, "lng": 151.2153, "description": "Sail-shaped performing arts centre, Australian icon",          "category": "heritage"},
    {"name": "Great Barrier Reef",     "region": "Queensland",        "country": "Australia",      "lat": -18.2871, "lng": 147.6992, "description": "World's largest coral reef system, 2,300 km long",            "category": "nature"},
    {"name": "Uluru",                  "region": "Northern Territory","country": "Australia",      "lat": -25.3444, "lng": 131.0369, "description": "Massive sandstone monolith, sacred Anangu site",              "category": "nature"},
    {"name": "Milford Sound",          "region": "Fiordland",         "country": "New Zealand",    "lat": -44.6414, "lng": 167.8972, "description": "Fjord carved by glaciers, waterfalls and rainforest",          "category": "nature"},
    {"name": "Bora Bora",              "region": "Society Islands",   "country": "French Polynesia","lat": -16.5004, "lng": -151.7415,"description": "Lush volcanic island surrounded by turquoise lagoon",          "category": "island"},
]


def seed_global():
    app = create_app()
    with app.app_context():
        existing = {d.name for d in Destination.query.all()}
        added = 0

        for d in GLOBAL_DESTINATIONS:
            if d["name"] in existing:
                continue
            dest = Destination(
                name=d["name"],
                region=d["region"],
                country=d["country"],
                lat=d["lat"],
                lng=d["lng"],
                description=d["description"],
                category=d["category"],
                best_time_to_visit=d.get("best_time_to_visit"),
                entry_fee_display=d.get("entry_fee_display"),
                rating=d.get("rating"),
                image_url=d.get("image_url"),
                highlights=d.get("highlights"),
            )
            db.session.add(dest)
            existing.add(d["name"])
            added += 1

        db.session.commit()
        print(f"Seeded {added} new global destinations ({len(existing)} total in database).")


if __name__ == "__main__":
    seed_global()
